# Generated by Django 5.2.7 on 2025-10-19 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_compra', models.CharField(max_length=200, verbose_name='Local da Compra')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_compra', models.DateField(verbose_name='Data da Compra')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('num_parcelas', models.IntegerField(default=1, verbose_name='Nº de Parcelas')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lancamentos.categoria')),
            ],
        ),
    ]
