# Generated by Django 5.2.7 on 2025-10-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='macro_categoria',
            field=models.CharField(choices=[('Essenciais', 'Essenciais'), ('Estilo de Vida', 'Estilo de Vida'), ('Prioridades', 'Prioridades'), ('Outras', 'Outras')], default='Outras', max_length=50),
        ),
    ]
