# Generated by Django 5.2.7 on 2025-10-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0003_categoria_user_lancamento_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='exemplos',
            field=models.TextField(blank=True, help_text='Ex: Contas de luz, água, internet...', null=True, verbose_name='Exemplos'),
        ),
    ]
