# Generated by Django 5.2.7 on 2025-10-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0004_categoria_exemplos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('macro_categoria', models.CharField(choices=[('Essenciais', 'Essenciais'), ('Estilo de Vida', 'Estilo de Vida'), ('Prioridades', 'Prioridades'), ('Outras', 'Outras')], default='Outras', max_length=50)),
                ('exemplos', models.TextField(blank=True, help_text='Ex: Contas de luz, água, internet...', null=True, verbose_name='Exemplos')),
            ],
            options={
                'verbose_name': 'Categoria Padrão',
                'verbose_name_plural': 'Categorias Padrão',
            },
        ),
    ]
