# Generated by Django 5.2.7 on 2025-10-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0005_categoriapadrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='metodo_pagamento',
            field=models.CharField(choices=[('Crédito', 'Crédito'), ('Débito', 'Débito'), ('PIX', 'PIX'), ('Dinheiro', 'Dinheiro')], default='Crédito', max_length=50),
        ),
    ]
