# Generated by Django 5.2.7 on 2025-10-24 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0008_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='limite_cartao',
        ),
        migrations.CreateModel(
            name='CartaoDeCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cartão')),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Limite')),
                ('dia_fechamento', models.IntegerField(verbose_name='Dia do Fechamento')),
                ('dia_vencimento', models.IntegerField(verbose_name='Dia do Vencimento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='lancamento',
            name='cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lancamentos.cartaodecredito'),
        ),
    ]
